### ISSUE TITLE
CI/CD support

### ISSUE THREAD

**Issue by FiniteReality** [FiniteReality/SourceLua#4]
We should probably have some form of CI/CD, so we can provide pre-compiled binaries with releases, or the latest build if necessary. This will integrate nicely with #3.

**Comment by FiniteReality** [comment]
To anybody looking to implement this, it would likely be best to use something like CircleCI, or at least something with up-to-date software

**Comment by Git-Jiro** [comment]
Some time ago I integrated TravisCI in a C++ project. It might be interesting to get to know another CI service like CircleCI as well.

I would like to work on this.

**Comment by FiniteReality** [comment]
Sure! It'd be nice if you left the configuration open enough to make integrating unit tests easier, and general tweaks in the future.

**Comment by Git-Jiro** [comment]
OK, I will check where unit tests would fit into the build

**Comment by Git-Jiro** [comment]
Short status-update: I am going to build a custom Docker container for this. Or are you aware of any container which is based on Debian stretch and has cmake installed so I can skip this step?

**Comment by Git-Jiro** [comment]
Please have a look at this PR: https://github.com/FiniteReality/SourceLua/pull/7

**Comment by FiniteReality** [comment]
Added in 5c9076b
